# Default Grid Configuration Defaults
DEFAULT_ROWS = 15
DEFAULT_COLS = 15
DEFAULT_OBSTACLE_DENSITY = 0.20  # 20%
DEFAULT_AGENT_COUNT = 3
DEFAULT_INITIAL_SIGNALS = 5
DEFAULT_DYNAMIC_FREQUENCY = 0.5
DEFAULT_DYNAMIC_DURATION = 100
DEFAULT_MAX_TICKS = 200
DEFAULT_SEED = 42

# UI Window and Layout Dimensions
DEFAULT_WINDOW_WIDTH = 1280
DEFAULT_WINDOW_HEIGHT = 800
DEFAULT_SIDEBAR_WIDTH = 300
DEFAULT_BOTTOM_BAR_HEIGHT = 100

# Cell Rendering Constants
MIN_CELL_SIZE = 12
MAX_CELL_SIZE = 60
DEFAULT_FPS = 60
DEFAULT_PLAYBACK_SPEED_TPS = 5

# Color Palettes
COLOR_FREE = "#1a1a2e"
COLOR_OBSTACLE = "#0f0f0f"
COLOR_OBSTACLE_HATCH = "#333333"
COLOR_SIGNAL_ACTIVE = "#e74c3c"
COLOR_SIGNAL_RESOLVED = "#2ecc71"
COLOR_BASE = "#3498db"
COLOR_GRID_LINE = "#2d2d44"
COLOR_RESERVATION_BORDER = "#f1c40f"
COLOR_HIGHLIGHT_WHITE = "#ffffff"
COLOR_HIGHLIGHT_BLACK = "#000000"
COLOR_HUD_TEXT_MUTED = "#8888aa"
COLOR_INSTRUCTIONS_TEXT = "#555577"
COLOR_BG_DARK = "#11111e"

# Per-agent unique color palette
AGENT_COLORS_PALETTE = [
    "#e74c3c",  # Red
    "#2ecc71",  # Green
    "#3498db",  # Blue
    "#f39c12",  # Orange
    "#9b59b6",  # Purple
    "#1abc9c",  # Teal
    "#e67e22",  # Pumpkin
    "#ecf0f1",  # Light grey
    "#fd79a8",  # Pink
    "#00cec9",  # Cyan
]
