[project]
name = "multi-agent-systems"
version = "0.1.0"
description = "Multi-Agent Systems cooperative course projects"
authors = [{ name = "culbec", email = "profir.alexx@gmail.com" }, { name = "tudormihaita", email = "tudor.mihaita03@gmail.com"}]
requires-python = ">=3.12"
dependencies = [
    "feedparser>=6.0.12",
    "newspaper4k[nlp]>=0.9.5",
    "numpy>=2.4.3",
    "pandas>=3.0.1",
    "plotly>=6.6.0",
    "pydantic>=2.13.2",
    "pytest>=9.0.3",
    "spade>=4.0.3",
    "spade-llm>=0.2.0",
    "click>=8.3",
    "streamlit>=1.50.0",
    "scikit-learn>=1.5.0",
    "aiofiles>=25.0",
    "gradio>=6.14.0",
    "pytest-asyncio>=1.3.0",
    "pygame-gui>=0.6.14",
    "pygame-ce>=2.5.7",
]

[tool.ruff.lint]
ignore = ["S101"]

[tool.pytest.ini_options]
pythonpath = ["."]
